"""TravelAgentState 的统一构建入口。"""

from app.agent.state import TravelAgentState


def create_initial_state(
    *,
    messages: list[dict],
    topic: str,
    session_id: str,
    user_action: str = "start_planning",
) -> TravelAgentState:
    """创建新规划或 trace 使用的完整初始状态。"""
    return {
        "messages": messages,
        "topic": topic,
        "user_intent": "",
        "granularity_level": "topic",
        "missing_info": [],
        "candidate_destinations": [],
        "selected_destination": "",
        "travel_dates": {},
        "season": "",
        "user_preferences": {},
        "budget": 0.0,
        "hard_constraints": [],
        "draft_itinerary": [],
        "current_itinerary": [],
        "current_stage": "",
        "next_action": "",
        "questions_to_ask": [],
        "modification_request": "",
        "affected_cards": [],
        "agent_response": "",
        "session_id": session_id,
        "planning_round": 0,
        "clarification_round": 0,
        "questions_asked": 0,
        "workflow_status": "running",
        "planning_goal": topic,
        "confirmed_facts": {},
        "assumptions": [],
        "agent_reports": {},
        "specialist_results": [],
        "agent_tasks": [],
        "workflow_events": [],
        "evidence_refs": [],
        "validation_results": {},
        "pending_question": "",
        "modification_scope": "",
        "time_candidates": [],
        "route_requests": [],
        "draft_cards": [],
        "card_dependencies": {},
        "revision_comparison": [],
        "user_action": user_action,
        "trip_brief": {"topic": topic, "granularity_level": "topic"},
        "profile_memory": [],
        "session_memory": [],
        "candidate_memory": [],
    }
